dist: xenial
language: python
python:
  - "3.7"

services:
  - docker
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build
      name: "conda cuda image"
      script:
        - docker build -t "yzs981130/conda-cuda" --build-arg "BASE_CUDA_VERSION=10.2" -f manywheel/Dockerfile .
        - docker push yzs981130/conda-cuda
